name: cineket
description: This app allows user to book cinema movie ticket in a few clicks with modern UI
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_size_text: ^3.0.0
  bloc: ^8.1.2
  cached_network_image: ^3.2.3
  dartz: ^0.10.1
  dio: ^5.3.2
  equatable: ^2.0.5
  firebase_core: ^2.15.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_flavor: ^3.1.1
  flutter_floating_bottom_bar: ^1.2.0
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.7
  intl: ^0.18.0

dev_dependencies:
  bloc_test: ^9.1.2
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.1
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/svg/
    - .env
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Black.ttf
          weight: 900
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato-Thin.ttf
          weight: 100
        - asset: assets/fonts/Lato-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Lato-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Lato-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Lato-ThinItalic.ttf
          weight: 100
          style: italic
